# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 738512ee17e6eaea7dca19f49f88cb0ec9a03ea1d492626a7277c5af059040167bf7400d0e977f1d054e4f6f6fb3a31027fd4610a3a38f257f4f8908b0cbdb67

test:
  secret_key_base: d101b010d2b8df035577bcd706d45fa30e6635a2161f6f58876a3099e7a92c5f6532bd81235800694d2a70c1c0be8f2eaf37b645505701f97abb6944d8d71788

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
